version: "3"

services:
  kafka-node:
    image: mahajan777/kafka-node:latest
    ports:
      - 9092:9092
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
