FROM mahajan777/streaming-base:latest
MAINTAINER Parul  Mahajan


# Expose ZooKeeper
EXPOSE 2181
USER root

ENTRYPOINT ["/apps/kafka/bin/zookeeper-server-start.sh"]
#RUN /apps/kafka/bin/zookeeper-server-start.sh
