#Download base image ubuntu 16.04
FROM mahajan777/base_image:latest

MAINTAINER Parul  Mahajan

COPY artifacts/SpringbootJWT-latest.jar /opt/

ENTRYPOINT ["java","-jar","/opt/SpringbootJWT-latest.jar"]